serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules: []
  create: true
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


replicaCount: 2

image:
  repository: naveenk0/hello-world
  tag: v1
  pullPolicy: IfNotPresent

containerPort: 3000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ""  # leave empty to use default ELB
      paths:
        - path: /
          pathType: Prefix
  tls: []

