apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: default

configMapGenerator:
  - name: app-config
    literals:
      - ENV=production
      - LOG_LEVEL=info

commonLabels:
  app: web
  environment: production

